### ISSUE TITLE
Separation symbol, cultureinfo

### ISSUE THREAD

**Issue by jpadron** [Daves-Astrophotography/UniUSBSQMServer#12]
Hi, congrats on this useful software.

I have my operating system in spanish. The decimal separator is a "," not a dot ".". With this configuration the server presents incorrect values because there is no separator in the read values . If I change my configuration to a dot everything is fine.

Thanks for your attention.
Jorge

**Comment by DaveAuld** [comment]
Morning Jorge, thanks for this feedback. I'll take a look into it. It shouldn't affect any device that communicates with server as the software passes the messages from the Unihedron devices downstream to the clients. It should only be affecting the local display of the data within the server.

**Comment by jpadron** [comment]
Hi!, yes, it doesn't affect but the interface shows wrong values (1940, instead of 19.40 or 19,40). The bortle scale is also affected, I think, as is shown as 9 all the time...
Thank you again.
Jorge

**Comment by DaveAuld** [comment]
@jpadron That is the bug fixed I hope, I switched my system back and forth from UK to Spanish and tested the changes and they appear to have worked fine. Let me know if there are any further issues seen. I will close the issue for the time being.

See the releases page for the latest versions. V1.3 Release
